In [1]:
# Importando a biblioteca Pandas
import pandas as pd

## Inspeção e tratamento da tabela de Mortes Violentas Intencionais (MVI)

Nesta etapa, serão selecionados e tratados os dados de Mortes Violentas Intencionais (MVI) por Unidade da Federação, referentes aos anos de 2023 e 2024.

In [2]:
# Definindo o caminho do arquivo original
arquivo = "../data/raw/anuario_seguranca_publica_2025.xlsx"

In [3]:
# Carregando o arquivo Excel
excel = pd.ExcelFile(arquivo)

# Lista as abas disponíveis
excel.sheet_names

['Índice',
 'T01',
 'T02',
 'P01',
 'Q01',
 'T03',
 'T04',
 'T05',
 'T06',
 'T07',
 'T08',
 'P02',
 'T09',
 'T10',
 'P03',
 'Q02',
 'Q03',
 'T11',
 'G26',
 'T12',
 'T13',
 'T14',
 'T15',
 'T16',
 'T17',
 'T18',
 'P04',
 'Q04',
 'Q05',
 'Q06',
 'T19',
 'P05',
 'T20',
 'T21',
 'P06',
 'T22',
 'T23',
 'T24',
 'T25',
 'T26',
 'T27',
 'T28',
 'T29',
 'T30',
 'T31',
 'T32',
 'T33',
 'Q07',
 'P07',
 'T34',
 'T35',
 'T36',
 'T37',
 'T38',
 'T39',
 'P08',
 'Q08',
 'T40',
 'T41',
 'T42',
 'T43',
 'T44',
 'T45',
 'T46',
 'T47',
 'T48',
 'T49',
 'T50',
 'T51',
 'T52',
 'T53',
 'P09',
 'P10',
 'G66',
 'P11',
 'P12',
 'T54',
 'T55',
 'T56',
 'T57',
 'T58',
 'T59',
 'T60',
 'T61',
 'T62',
 'T63',
 'T64',
 'T65',
 'T66',
 'T67',
 'T68',
 'T69',
 'T70',
 'P13',
 'T71',
 'G79',
 'T72',
 'T73',
 'T74',
 'T75',
 'T76',
 'T77',
 'T78',
 'T79',
 'T80',
 'T81',
 'T82',
 'T83',
 'T84',
 'T85',
 'G80',
 'T86',
 'T87',
 'T88',
 'T89',
 'T90',
 'T91',
 'T92',
 'T93',
 'T94',
 'T95',
 'T96',
 'T97',
 'G81',
 'T98',
 'T99',
 'T100',
 'T101',
 'T102',
 'G82',
 'P14',
 'T103',
 'T104',
 'T105',
 'T106',
 'T107',
 'T108',
 'T109',
 'T110',
 'T111',
 'T112',
 'T113',
 'T114',
 'T115',
 'T116',
 'G86',
 'T117',
 'T118',
 'T119',
 'T120',
 'T121',
 'T122',
 'T123',
 'T124',
 'T125',
 'T126',
 'T127',
 'T128',
 'T129',
 'T130',
 'T131',
 'T132',
 'T133',
 'T134',
 'T135',
 'T136',
 'T137',
 'T138',
 'T139',
 'P15',
 'T140',
 'T141',
 'T142',
 'T143',
 'T144',
 'T145',
 'G90',
 'G91',
 'P16']

In [4]:
tabelas_projeto = ['T01', 'T04', 'T13', 'T24']

for tabela in tabelas_projeto:
    print(tabela, "->", tabela in excel.sheet_names)

T01 -> True
T04 -> True
T13 -> True
T24 -> True

In [5]:
# Carrega a Tabela 01 sem definir cabeçalho
df_t01 = pd.read_excel(arquivo, sheet_name='T01', header=None)

# Exibe as 15 primeiras linhas
df_t01.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,TABELA 01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(Voltar ao índice)
1,Mortes violentas intencionais (1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Brasil e Unidades da Federação – 2023-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Brasil e Unidades da Federação,Crimes Violentos Letais Intencionais - CVLI,NaN,NaN,NaN,NaN,NaN,Policiais Civis e Militares Vítimas de CVLI,NaN,Morte Decorrente de Intervenção Policial (em s...,NaN,Mortes Violentas Intencionais - MVI,NaN,NaN,NaN,NaN
5,NaN,Homicídio Doloso,NaN,Latrocínio,NaN,Lesão Corporal Seguida de Morte,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Ns. Absolutos,NaN,Ns. Absolutos,NaN,Ns. Absolutos,NaN,Ns. Absolutos,NaN,Ns. Absolutos,NaN,Ns. Absolutos,NaN,Taxa (2),NaN,Variação (%)
8,NaN,2023 (3),2024.0,2023 (3),2024.0,2023 (3),2024.0,2023 (3),2024,2023 (3),2024.0,2023 (3),2024.0,2023,2024.000000,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Brasil,38653,36427.0,1002,965.0,628,760.0,178,170,6413,6243.0,46441,44127.0,21.937677,20.757466,-5.379835
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Acre,190,164.0,5,1.0,4,4.0,-,-,15,10.0,214,179.0,24.413004,20.326334,-16.739726
13,Alagoas,1122,1054.0,18,6.0,4,6.0,2,4,66,75.0,1210,1141.0,37.593903,35.433638,-5.746317
14,Amapá,307,218.0,13,4.0,16,3.0,-,-,183,137.0,519,362.0,64.946116,45.090099,-30.573063

In [ ]:
# Seleciona as linhas e colunas referentes ao MVI
mvi = df_t01.iloc[10:39, [0, 11, 12, 13, 14]].copy()

# Os primeiros registros
mvi.head()

         0      11       12         13         14
10   Brasil  46441  44127.0  21.937677  20.757466
11      NaN    NaN      NaN        NaN        NaN
12     Acre    214    179.0  24.413004  20.326334
13  Alagoas   1210   1141.0  37.593903  35.433638
14    Amapá    519    362.0  64.946116  45.090099

In [7]:
# Renomeia as colunas selecionadas
mvi.columns = [
    'uf',
    'mvi_2023',
    'mvi_2024',
    'taxa_2023',
    'taxa_2024'
]

mvi.head()

         uf mvi_2023  mvi_2024  taxa_2023  taxa_2024
10   Brasil    46441   44127.0  21.937677  20.757466
11      NaN      NaN       NaN        NaN        NaN
12     Acre      214     179.0  24.413004  20.326334
13  Alagoas     1210    1141.0  37.593903  35.433638
14    Amapá      519     362.0  64.946116  45.090099

In [8]:
# Removendo linhas totalmente vazias
mvi = mvi.dropna(how='all')

mvi.head()

          uf mvi_2023  mvi_2024  taxa_2023  taxa_2024
10    Brasil    46441   44127.0  21.937677  20.757466
12      Acre      214     179.0  24.413004  20.326334
13   Alagoas     1210    1141.0  37.593903  35.433638
14     Amapá      519     362.0  64.946116  45.090099
15  Amazonas     1406    1173.0  33.155912  27.398803

In [9]:
# Exibe os últimos registros
mvi.tail()

                uf mvi_2023  mvi_2024  taxa_2023  taxa_2024
34         Roraima      177     133.0  25.457736  18.554869
35  Santa Catarina      674     685.0   8.502359   8.500403
36   São Paulo (5)     3480    3751.0   7.589873   8.159102
37         Sergipe      689     522.0  30.192893  22.784044
38       Tocantins      430     312.0  27.437626  19.780111

In [10]:
# Verificando a quantidade de linhas e colunas
mvi.shape

(28, 5)

In [11]:
# Verificando os tipos das colunas
mvi.dtypes

uf               str
mvi_2023      object
mvi_2024     float64
taxa_2023     object
taxa_2024    float64
dtype: object

In [12]:
# Verifica os tipos dos valores da coluna
mvi['mvi_2023'].apply(type).value_counts()

mvi_2023
<class 'int'>    28
Name: count, dtype: int64

In [13]:
# Verifica os tipos dos valores da coluna
mvi['taxa_2023'].apply(type).value_counts()

taxa_2023
<class 'float'>    28
Name: count, dtype: int64

In [14]:
# Convertendo as ocorrências para valores numéricos
mvi['mvi_2023'] = pd.to_numeric(mvi['mvi_2023'])
mvi['mvi_2024'] = pd.to_numeric(mvi['mvi_2024']).astype(int)

# Convertendo as taxas para valores numéricos
mvi['taxa_2023'] = pd.to_numeric(mvi['taxa_2023'])
mvi['taxa_2024'] = pd.to_numeric(mvi['taxa_2024'])

In [15]:
# Conferindo os tipos após a conversão
mvi.dtypes

uf               str
mvi_2023       int64
mvi_2024       int64
taxa_2023    float64
taxa_2024    float64
dtype: object

In [16]:
# Verificando valores nulos
mvi.isnull().sum()

uf           0
mvi_2023     0
mvi_2024     0
taxa_2023    0
taxa_2024    0
dtype: int64

In [17]:
# Transformação para o formato: uf | ano | indicador | ocorrencias | taxa_100_mil.

# Cria a base de MVI para 2023
mvi_2023 = mvi[['uf', 'mvi_2023', 'taxa_2023']].copy()

# Padroniza os nomes das colunas
mvi_2023.columns = ['uf', 'ocorrencias', 'taxa_100_mil']

# Adiciona o ano e o indicador
mvi_2023['ano'] = 2023
mvi_2023['indicador'] = 'MVI'

# Cria a base de MVI para 2024
mvi_2024 = mvi[['uf', 'mvi_2024', 'taxa_2024']].copy()

# Padroniza os nomes das colunas
mvi_2024.columns = ['uf', 'ocorrencias', 'taxa_100_mil']

# Adiciona o ano e o indicador
mvi_2024['ano'] = 2024
mvi_2024['indicador'] = 'MVI'

In [18]:
# Unindo os dados de 2023 e 2024
mvi_long = pd.concat([mvi_2023, mvi_2024], ignore_index=True)

# Definindo a ordem das colunas
mvi_long = mvi_long[
    ['uf', 'ano', 'indicador', 'ocorrencias', 'taxa_100_mil']
]

# Exibe o resultado da transformação
mvi_long.head()

         uf   ano indicador  ocorrencias  taxa_100_mil
0    Brasil  2023       MVI        46441     21.937677
1      Acre  2023       MVI          214     24.413004
2   Alagoas  2023       MVI         1210     37.593903
3     Amapá  2023       MVI          519     64.946116
4  Amazonas  2023       MVI         1406     33.155912

In [19]:
# Verificando as dimensões da base tratada
mvi_long.shape

(56, 5)

In [20]:
# Verificando os últimos registros
mvi_long.tail()

                uf   ano indicador  ocorrencias  taxa_100_mil
51         Roraima  2024       MVI          133     18.554869
52  Santa Catarina  2024       MVI          685      8.500403
53   São Paulo (5)  2024       MVI         3751      8.159102
54         Sergipe  2024       MVI          522     22.784044
55       Tocantins  2024       MVI          312     19.780111

## Inspeção e tratamento da tabela de Latrocínio

Nesta etapa, serão analisados os dados de latrocínio por Unidade da Federação, considerando o número de vítimas e o número de ocorrências nos anos de 2023 e 2024.

In [21]:
# Carrega a Tabela 04 sem definir cabeçalho
df_t04 = pd.read_excel(
    arquivo,
    sheet_name='T04',
    header=None
)

# Exibindo as 15 primeiras linhas
df_t04.head(15)

,0,1,2,3,4,5,6,7,8,9,10
0,TABELA 04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(Voltar ao índice)
1,"Latrocínio, por número de vítimas e número de ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Brasil e Unidades da Federação – 2023-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Brasil e Unidades da Federação,Latrocínio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Nº de Vítimas,NaN,NaN,NaN,NaN,Nº de Ocorrências,NaN,NaN,NaN,NaN
6,NaN,Ns. Absolutos,NaN,Taxas (1),NaN,Variação (%),Ns. Absolutos,NaN,Taxas (1),NaN,Variação (%)
7,NaN,2023 (2),2024.0,2023,2024.000000,NaN,2023 (2),2024.0,2023,2024.000000,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Brasil,1002,965.0,0.473322,0.453939,-4.095176,979,944.0,0.462457,0.444060,-3.978129
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Acre,5,1.0,0.570397,0.113555,-80.091957,4,1.0,0.456318,0.113555,-75.114946
12,Alagoas,18,6.0,0.559248,0.186329,-66.682163,18,5.0,0.559248,0.155274,-72.235136
13,Amapá,13,4.0,1.626781,0.498233,-69.373072,13,4.0,1.626781,0.498233,-69.373072
14,Amazonas,36,22.0,0.848942,0.513874,-39.468966,35,22.0,0.825361,0.513874,-37.739508

In [22]:
# Selecionando os dados de vítimas e ocorrências de latrocínio
latrocinio = df_t04.iloc[9:38, [0, 1, 2, 3, 4, 6, 7, 8, 9]].copy()

latrocinio.head()

          0     1      2         3         4    6      7         8         9
9    Brasil  1002  965.0  0.473322  0.453939  979  944.0  0.462457  0.444060
10      NaN   NaN    NaN       NaN       NaN  NaN    NaN       NaN       NaN
11     Acre     5    1.0  0.570397  0.113555    4    1.0  0.456318  0.113555
12  Alagoas    18    6.0  0.559248  0.186329   18    5.0  0.559248  0.155274
13    Amapá    13    4.0  1.626781  0.498233   13    4.0  1.626781  0.498233

In [23]:
# Renomeando as colunas
latrocinio.columns = [
    'uf',
    'vitimas_2023',
    'vitimas_2024',
    'taxa_vitimas_2023',
    'taxa_vitimas_2024',
    'ocorrencias_2023',
    'ocorrencias_2024',
    'taxa_ocorrencias_2023',
    'taxa_ocorrencias_2024'
]

# Removendo linhas vazias
latrocinio = latrocinio.dropna(how='all')

latrocinio.head()

,uf,vitimas_2023,vitimas_2024,taxa_vitimas_2023,taxa_vitimas_2024,ocorrencias_2023,ocorrencias_2024,taxa_ocorrencias_2023,taxa_ocorrencias_2024
9,Brasil,1002,965.0,0.473322,0.453939,979,944.0,0.462457,0.444060
11,Acre,5,1.0,0.570397,0.113555,4,1.0,0.456318,0.113555
12,Alagoas,18,6.0,0.559248,0.186329,18,5.0,0.559248,0.155274
13,Amapá,13,4.0,1.626781,0.498233,13,4.0,1.626781,0.498233
14,Amazonas,36,22.0,0.848942,0.513874,35,22.0,0.825361,0.513874

In [24]:
# Verifica a quantidade de linhas e colunas
latrocinio.shape

(28, 9)

In [25]:
# Verifica os últimos registros
latrocinio.tail()

,uf,vitimas_2023,vitimas_2024,taxa_vitimas_2023,taxa_vitimas_2024,ocorrencias_2023,ocorrencias_2024,taxa_ocorrencias_2023,taxa_ocorrencias_2024
33,Roraima,9,6.0,1.294461,0.837062,9,6.0,1.294461,0.837062
34,Santa Catarina,11,16.0,0.138763,0.198550,11,16.0,0.138763,0.198550
35,São Paulo,166,170.0,0.362046,0.369781,163,166.0,0.355503,0.361080
36,Sergipe,6,7.0,0.262928,0.305533,6,7.0,0.262928,0.305533
37,Tocantins,19,6.0,1.21236,0.380387,17,6.0,1.084743,0.380387

In [26]:
# Verifica valores nulos
latrocinio.isnull().sum()

uf                       0
vitimas_2023             0
vitimas_2024             0
taxa_vitimas_2023        0
taxa_vitimas_2024        0
ocorrencias_2023         0
ocorrencias_2024         0
taxa_ocorrencias_2023    0
taxa_ocorrencias_2024    0
dtype: int64

In [27]:
# Verifica os tipos das colunas
latrocinio.dtypes

uf                           str
vitimas_2023              object
vitimas_2024             float64
taxa_vitimas_2023         object
taxa_vitimas_2024        float64
ocorrencias_2023          object
ocorrencias_2024         float64
taxa_ocorrencias_2023     object
taxa_ocorrencias_2024    float64
dtype: object

In [28]:
# Definindo as colunas que precisam ser verificadas
colunas_verificar = [
    'vitimas_2023',
    'taxa_vitimas_2023',
    'ocorrencias_2023',
    'taxa_ocorrencias_2023'
]

# Verificando os tipos dos valores de cada coluna
for coluna in colunas_verificar:
    print(f"\n{coluna}")
    print(latrocinio[coluna].apply(type).value_counts())

vitimas_2023
vitimas_2023
<class 'int'>    28
Name: count, dtype: int64

taxa_vitimas_2023
taxa_vitimas_2023
<class 'float'>    28
Name: count, dtype: int64

ocorrencias_2023
ocorrencias_2023
<class 'int'>    28
Name: count, dtype: int64

taxa_ocorrencias_2023
taxa_ocorrencias_2023
<class 'float'>    28
Name: count, dtype: int64

In [29]:
# Convertendo contagens para inteiro
latrocinio['vitimas_2023'] = pd.to_numeric(
    latrocinio['vitimas_2023']
).astype(int)

latrocinio['vitimas_2024'] = pd.to_numeric(
    latrocinio['vitimas_2024']
).astype(int)

latrocinio['ocorrencias_2023'] = pd.to_numeric(
    latrocinio['ocorrencias_2023']
).astype(int)

latrocinio['ocorrencias_2024'] = pd.to_numeric(
    latrocinio['ocorrencias_2024']
).astype(int)

# Convertendo taxas para valores numéricos
latrocinio['taxa_vitimas_2023'] = pd.to_numeric(
    latrocinio['taxa_vitimas_2023']
)

latrocinio['taxa_vitimas_2024'] = pd.to_numeric(
    latrocinio['taxa_vitimas_2024']
)

latrocinio['taxa_ocorrencias_2023'] = pd.to_numeric(
    latrocinio['taxa_ocorrencias_2023']
)

latrocinio['taxa_ocorrencias_2024'] = pd.to_numeric(
    latrocinio['taxa_ocorrencias_2024']
)

In [30]:
# Confererindo os tipos após conversão
latrocinio.dtypes

uf                           str
vitimas_2023               int64
vitimas_2024               int64
taxa_vitimas_2023        float64
taxa_vitimas_2024        float64
ocorrencias_2023           int64
ocorrencias_2024           int64
taxa_ocorrencias_2023    float64
taxa_ocorrencias_2024    float64
dtype: object

In [31]:
# Transformando a tabela para o formato longo, preservando a diferença entre vítimas e ocorrências
# Dados de vítimas - 2023
latrocinio_vitimas_2023 = latrocinio[
    ['uf', 'vitimas_2023', 'taxa_vitimas_2023']
].copy()

latrocinio_vitimas_2023.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

latrocinio_vitimas_2023['ano'] = 2023
latrocinio_vitimas_2023['indicador'] = 'Latrocínio - vítimas'


# Dados de vítimas - 2024
latrocinio_vitimas_2024 = latrocinio[
    ['uf', 'vitimas_2024', 'taxa_vitimas_2024']
].copy()

latrocinio_vitimas_2024.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

latrocinio_vitimas_2024['ano'] = 2024
latrocinio_vitimas_2024['indicador'] = 'Latrocínio - vítimas'

In [32]:
# Dados de ocorrências - 2023
latrocinio_ocorrencias_2023 = latrocinio[
    ['uf', 'ocorrencias_2023', 'taxa_ocorrencias_2023']
].copy()

latrocinio_ocorrencias_2023.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

latrocinio_ocorrencias_2023['ano'] = 2023
latrocinio_ocorrencias_2023['indicador'] = 'Latrocínio - ocorrências'


# Dados de ocorrências - 2024
latrocinio_ocorrencias_2024 = latrocinio[
    ['uf', 'ocorrencias_2024', 'taxa_ocorrencias_2024']
].copy()

latrocinio_ocorrencias_2024.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

latrocinio_ocorrencias_2024['ano'] = 2024
latrocinio_ocorrencias_2024['indicador'] = 'Latrocínio - ocorrências'

In [33]:
# Juntando os dados de vítimas e ocorrências
latrocinio_long = pd.concat([
    latrocinio_vitimas_2023,
    latrocinio_vitimas_2024,
    latrocinio_ocorrencias_2023,
    latrocinio_ocorrencias_2024
], ignore_index=True)

# Padronizando a ordem das colunas
latrocinio_long = latrocinio_long[
    ['uf', 'ano', 'indicador', 'ocorrencias', 'taxa_100_mil']
]

# Exibindo resultado
latrocinio_long.head()

         uf   ano             indicador  ocorrencias  taxa_100_mil
0    Brasil  2023  Latrocínio - vítimas         1002      0.473322
1      Acre  2023  Latrocínio - vítimas            5      0.570397
2   Alagoas  2023  Latrocínio - vítimas           18      0.559248
3     Amapá  2023  Latrocínio - vítimas           13      1.626781
4  Amazonas  2023  Latrocínio - vítimas           36      0.848942

In [34]:
# Verifica as dimensões da base tratada
latrocinio_long.shape

(112, 5)

In [35]:
# Verifica a quantidade de registros por indicador
latrocinio_long['indicador'].value_counts()

indicador
Latrocínio - vítimas        56
Latrocínio - ocorrências    56
Name: count, dtype: int64

In [36]:
# Verifica valores nulos
latrocinio_long.isnull().sum()
latrocinio_long.isnull().sum()

uf              0
ano             0
indicador       0
ocorrencias     0
taxa_100_mil    0
dtype: int64

## Inspeção e tratamento da tabela de Roubo e Furto de Celulares

Nesta etapa, são analisados os dados de roubo e furto de celulares por Unidade da Federação, considerando os números absolutos e as taxas por 100 mil habitantes nos anos de 2023 e 2024.

In [37]:
# Carregando a Tabela 13 sem definir cabeçalho
df_t13 = pd.read_excel(
    arquivo,
    sheet_name='T13',
    header=None
)

# Exibindo as 15 primeiras linhas
df_t13.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,TABELA 13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(Voltar ao índice)
1,Roubo e Furto de celulares (1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Brasil e Unidades da Federação – 2023-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Brasil e Unidades da Federação,Roubo de celulares,NaN,NaN,NaN,NaN,Furto de celulares,NaN,NaN,NaN,NaN,Roubo e Furto de celulares,NaN,NaN,NaN,NaN
5,NaN,Ns. Absolutos,NaN,Taxa (2),NaN,Variação (%),Ns. Absolutos,NaN,Taxa (2),NaN,Variação (%),Ns. Absolutos,NaN,Taxa (2),NaN,Variação (%)
6,NaN,2023 (3),2024.0,2023,2024.000000,NaN,2023 (3),2024.0,2023,2024.000000,NaN,2023 (3),2024.0,2023,2024.000000,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Brasil,455124,374688.0,214.990274,176.254300,-18.017547,514073,476116.0,242.836447,223.966319,-7.770715,969197,850804.0,457.826721,400.220619,-12.582512
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Acre,2390,1703.0,272.649906,193.384062,-29.07239,1586,1583.0,180.930021,179.757469,-0.648069,3976,3286.0,453.579927,373.141531,-17.734117
11,Alagoas,5632,4537.0,174.982531,140.896070,-19.479922,4527,4339.0,140.650909,134.747201,-4.197419,10159,8876.0,315.63344,275.643271,-12.669814
12,Amapá,3923,2774.0,490.912549,345.524683,-29.615838,3056,2921.0,382.418749,363.834751,-4.859594,6979,5695.0,873.331298,709.359434,-18.775448
13,Amazonas,26690,22825.0,629.396371,533.143792,-15.29284,12623,12782.0,297.672177,298.560523,0.298431,39313,35607.0,927.068548,831.704315,-10.286643
14,Bahia,44814,35423.0,302.209092,238.530480,-21.071044,28848,26279.0,194.540275,176.956850,-9.03845,73662,61702.0,496.749367,415.487330,-16.35876

In [38]:
# Selecionando os dados de roubo, furto e total de celulares
celulares = df_t13.iloc[
    8:37,
    [0, 1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14]
].copy()

# Exibindo os primeiros registros
celulares.head()

,0,1,2,3,4,6,7,8,9,11,12,13,14
8,Brasil,455124,374688.0,214.990274,176.254300,514073,476116.0,242.836447,223.966319,969197,850804.0,457.826721,400.220619
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Acre,2390,1703.0,272.649906,193.384062,1586,1583.0,180.930021,179.757469,3976,3286.0,453.579927,373.141531
11,Alagoas,5632,4537.0,174.982531,140.896070,4527,4339.0,140.650909,134.747201,10159,8876.0,315.63344,275.643271
12,Amapá,3923,2774.0,490.912549,345.524683,3056,2921.0,382.418749,363.834751,6979,5695.0,873.331298,709.359434

In [39]:
# Renomeando as colunas selecionadas
celulares.columns = [
    'uf',
    'roubo_2023',
    'roubo_2024',
    'taxa_roubo_2023',
    'taxa_roubo_2024',
    'furto_2023',
    'furto_2024',
    'taxa_furto_2023',
    'taxa_furto_2024',
    'roubo_furto_2023',
    'roubo_furto_2024',
    'taxa_roubo_furto_2023',
    'taxa_roubo_furto_2024'
]

# Remove linhas totalmente vazias
celulares = celulares.dropna(how='all')

# Exibe os primeiros registros
celulares.head()

,uf,roubo_2023,roubo_2024,taxa_roubo_2023,taxa_roubo_2024,furto_2023,furto_2024,taxa_furto_2023,taxa_furto_2024,roubo_furto_2023,roubo_furto_2024,taxa_roubo_furto_2023,taxa_roubo_furto_2024
8,Brasil,455124,374688.0,214.990274,176.254300,514073,476116.0,242.836447,223.966319,969197,850804.0,457.826721,400.220619
10,Acre,2390,1703.0,272.649906,193.384062,1586,1583.0,180.930021,179.757469,3976,3286.0,453.579927,373.141531
11,Alagoas,5632,4537.0,174.982531,140.896070,4527,4339.0,140.650909,134.747201,10159,8876.0,315.63344,275.643271
12,Amapá,3923,2774.0,490.912549,345.524683,3056,2921.0,382.418749,363.834751,6979,5695.0,873.331298,709.359434
13,Amazonas,26690,22825.0,629.396371,533.143792,12623,12782.0,297.672177,298.560523,39313,35607.0,927.068548,831.704315

In [40]:
# Verifica a quantidade de linhas e colunas
celulares.shape

(28, 13)

In [41]:
# Verifica os últimos registros
celulares.tail()

,uf,roubo_2023,roubo_2024,taxa_roubo_2023,taxa_roubo_2024,furto_2023,furto_2024,taxa_furto_2023,taxa_furto_2024,roubo_furto_2023,roubo_furto_2024,taxa_roubo_furto_2023,taxa_roubo_furto_2024
32,Roraima,1334,956.0,191.867907,133.371838,1942,1669.0,279.315949,232.842676,3276,2625.0,471.183857,366.214514
33,Santa Catarina,3482,2986.0,43.924648,37.054314,18609,17614.0,234.748358,218.578258,22091,20600.0,278.673006,255.632572
34,São Paulo,150159,118181.0,327.496474,257.065019,173957,152307.0,379.399864,331.295233,324116,270488.0,706.896337,588.360252
35,Sergipe,3906,2867.0,171.166094,125.137654,5232,4709.0,229.273171,205.536523,9138,7576.0,400.439265,330.674176
36,Tocantins,1056,1023.0,67.381704,64.855941,2750,3018.0,175.473187,191.334536,3806,4041.0,242.854891,256.190477

In [42]:
# Verifica valores nulos
celulares.isnull().sum()

uf                       0
roubo_2023               0
roubo_2024               0
taxa_roubo_2023          0
taxa_roubo_2024          0
furto_2023               0
furto_2024               0
taxa_furto_2023          0
taxa_furto_2024          0
roubo_furto_2023         0
roubo_furto_2024         0
taxa_roubo_furto_2023    0
taxa_roubo_furto_2024    0
dtype: int64

In [43]:
# Verificando os tipos das colunas
celulares.dtypes

uf                           str
roubo_2023                object
roubo_2024               float64
taxa_roubo_2023           object
taxa_roubo_2024          float64
furto_2023                object
furto_2024               float64
taxa_furto_2023           object
taxa_furto_2024          float64
roubo_furto_2023          object
roubo_furto_2024         float64
taxa_roubo_furto_2023     object
taxa_roubo_furto_2024    float64
dtype: object

In [44]:
# Definindo as colunas que precisam ser verificadas
colunas_verificar = [
    'roubo_2023',
    'taxa_roubo_2023',
    'furto_2023',
    'taxa_furto_2023',
    'roubo_furto_2023',
    'taxa_roubo_furto_2023'
]

# Verificando os tipos dos valores de cada coluna
for coluna in colunas_verificar:
    print(f"\n{coluna}")
    print(celulares[coluna].apply(type).value_counts())

roubo_2023
roubo_2023
<class 'int'>    28
Name: count, dtype: int64

taxa_roubo_2023
taxa_roubo_2023
<class 'float'>    28
Name: count, dtype: int64

furto_2023
furto_2023
<class 'int'>    28
Name: count, dtype: int64

taxa_furto_2023
taxa_furto_2023
<class 'float'>    28
Name: count, dtype: int64

roubo_furto_2023
roubo_furto_2023
<class 'int'>    28
Name: count, dtype: int64

taxa_roubo_furto_2023
taxa_roubo_furto_2023
<class 'float'>    28
Name: count, dtype: int64

In [45]:
# Definindo as colunas de números absolutos com listas
colunas_inteiras = [
    'roubo_2023',
    'roubo_2024',
    'furto_2023',
    'furto_2024',
    'roubo_furto_2023',
    'roubo_furto_2024'
]

# Convertendo os números absolutos para inteiro
for coluna in colunas_inteiras:
    celulares[coluna] = pd.to_numeric(celulares[coluna]).astype(int)


# Definindo as colunas de taxas
colunas_taxas = [
    'taxa_roubo_2023',
    'taxa_roubo_2024',
    'taxa_furto_2023',
    'taxa_furto_2024',
    'taxa_roubo_furto_2023',
    'taxa_roubo_furto_2024'
]

# Convertendo as taxas para valores numéricos
for coluna in colunas_taxas:
    celulares[coluna] = pd.to_numeric(celulares[coluna])

In [46]:
# Conferindo os tipos após conversão
celulares.dtypes

uf                           str
roubo_2023                 int64
roubo_2024                 int64
taxa_roubo_2023          float64
taxa_roubo_2024          float64
furto_2023                 int64
furto_2024                 int64
taxa_furto_2023          float64
taxa_furto_2024          float64
roubo_furto_2023           int64
roubo_furto_2024           int64
taxa_roubo_furto_2023    float64
taxa_roubo_furto_2024    float64
dtype: object

In [47]:
# Criando a base de roubo de celulares para 2023
roubo_2023 = celulares[
    ['uf', 'roubo_2023', 'taxa_roubo_2023']
].copy()

roubo_2023.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

roubo_2023['ano'] = 2023
roubo_2023['indicador'] = 'Roubo de celulares'


# Criando a base de roubo de celulares para 2024
roubo_2024 = celulares[
    ['uf', 'roubo_2024', 'taxa_roubo_2024']
].copy()

roubo_2024.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

roubo_2024['ano'] = 2024
roubo_2024['indicador'] = 'Roubo de celulares'

In [48]:
# Juntando os dados de roubo de 2023 e 2024
roubo_long = pd.concat(
    [roubo_2023, roubo_2024],
    ignore_index=True
)

# Padroniza a ordem das colunas
roubo_long = roubo_long[
    ['uf', 'ano', 'indicador', 'ocorrencias', 'taxa_100_mil']
]

roubo_long.head()

         uf   ano           indicador  ocorrencias  taxa_100_mil
0    Brasil  2023  Roubo de celulares       455124    214.990274
1      Acre  2023  Roubo de celulares         2390    272.649906
2   Alagoas  2023  Roubo de celulares         5632    174.982531
3     Amapá  2023  Roubo de celulares         3923    490.912549
4  Amazonas  2023  Roubo de celulares        26690    629.396371

In [49]:
# Criando a base de furto de celulares para 2023
furto_2023 = celulares[
    ['uf', 'furto_2023', 'taxa_furto_2023']
].copy()

furto_2023.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

furto_2023['ano'] = 2023
furto_2023['indicador'] = 'Furto de celulares'


# Criando a base de furto de celulares para 2024
furto_2024 = celulares[
    ['uf', 'furto_2024', 'taxa_furto_2024']
].copy()

furto_2024.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

furto_2024['ano'] = 2024
furto_2024['indicador'] = 'Furto de celulares'

In [50]:
# Juntando os dados de furto de 2023 e 2024
furto_long = pd.concat(
    [furto_2023, furto_2024],
    ignore_index=True
)

# Padroniza a ordem das colunas
furto_long = furto_long[
    ['uf', 'ano', 'indicador', 'ocorrencias', 'taxa_100_mil']
]

furto_long.head()

         uf   ano           indicador  ocorrencias  taxa_100_mil
0    Brasil  2023  Furto de celulares       514073    242.836447
1      Acre  2023  Furto de celulares         1586    180.930021
2   Alagoas  2023  Furto de celulares         4527    140.650909
3     Amapá  2023  Furto de celulares         3056    382.418749
4  Amazonas  2023  Furto de celulares        12623    297.672177

In [51]:
# Criando a base de roubo e furto de celulares para 2023
roubo_furto_2023 = celulares[
    ['uf', 'roubo_furto_2023', 'taxa_roubo_furto_2023']
].copy()

roubo_furto_2023.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

roubo_furto_2023['ano'] = 2023
roubo_furto_2023['indicador'] = 'Roubo e furto de celulares'


# Criando a base de roubo e furto de celulares para 2024
roubo_furto_2024 = celulares[
    ['uf', 'roubo_furto_2024', 'taxa_roubo_furto_2024']
].copy()

roubo_furto_2024.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

roubo_furto_2024['ano'] = 2024
roubo_furto_2024['indicador'] = 'Roubo e furto de celulares'

In [52]:
# Juntando os dados de 2023 e 2024
roubo_furto_long = pd.concat(
    [roubo_furto_2023, roubo_furto_2024],
    ignore_index=True
)

# Padroniza a ordem das colunas
roubo_furto_long = roubo_furto_long[
    ['uf', 'ano', 'indicador', 'ocorrencias', 'taxa_100_mil']
]

roubo_furto_long.head()

         uf   ano                   indicador  ocorrencias  taxa_100_mil
0    Brasil  2023  Roubo e furto de celulares       969197    457.826721
1      Acre  2023  Roubo e furto de celulares         3976    453.579927
2   Alagoas  2023  Roubo e furto de celulares        10159    315.633440
3     Amapá  2023  Roubo e furto de celulares         6979    873.331298
4  Amazonas  2023  Roubo e furto de celulares        39313    927.068548

In [53]:
# Une roubo, furto e total de celulares
celulares_long = pd.concat([
    roubo_long,
    furto_long,
    roubo_furto_long
], ignore_index=True)

celulares_long.head()

         uf   ano           indicador  ocorrencias  taxa_100_mil
0    Brasil  2023  Roubo de celulares       455124    214.990274
1      Acre  2023  Roubo de celulares         2390    272.649906
2   Alagoas  2023  Roubo de celulares         5632    174.982531
3     Amapá  2023  Roubo de celulares         3923    490.912549
4  Amazonas  2023  Roubo de celulares        26690    629.396371

In [54]:
# Verificando a quantidade de linhas e colunas
celulares_long.shape

(168, 5)

In [55]:
# Verificando a quantidade de registros por indicador
celulares_long['indicador'].value_counts()

indicador
Roubo de celulares            56
Furto de celulares            56
Roubo e furto de celulares    56
Name: count, dtype: int64

In [56]:
# Verificando se existem valores nulos
celulares_long.isnull().sum()

uf              0
ano             0
indicador       0
ocorrencias     0
taxa_100_mil    0
dtype: int64

## Inspeção e tratamento da Tabela de Homicídios de Mulheres e Feminicídios

Nesta etapa, são analisados os dados de homicídios de mulheres e feminicídios por Unidade da Federação, considerando os números absolutos, as taxas e a proporção de feminicídios nos anos de 2023 e 2024.

In [57]:
# Carregando a Tabela 24 sem cabeçalho
df_t24 = pd.read_excel(
    arquivo,
    sheet_name='T24',
    header=None
)

# Exibe as 15 primeiras linhas
df_t24.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,TABELA 24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(Voltar ao índice)
1,Homicídios de mulheres e feminicídios (1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Brasil e Unidades da Federação – 2023-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Brasil e Unidades da Federação,Homicídios (incluindo feminicídios),NaN,NaN,NaN,NaN,Feminicídios,NaN,NaN,NaN,NaN,Proporção de feminicídios em relação aos homic...,NaN
5,NaN,Vítimas Mulheres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Ns. Absolutos,NaN,Taxa (2),NaN,Variação\n(%),Ns. Absolutos,NaN,Taxa (2),NaN,Variação (%),Em percentual (%),NaN
7,NaN,2023 (3),2024.0,2023,2024.000000,NaN,2023 (3),2024.0,2023,2024.000000,NaN,2023 (3),2024
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Brasil,3937,3700.0,3.630458,3.396943,-6.432121,1475,1492.0,1.360154,1.369794,0.708767,37.465075,40.324324
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Acre,15,13.0,3.432942,2.962058,-13.716624,10,8.0,2.288628,1.822805,-20.353806,66.666667,61.538462
12,Alagoas,80,73.0,4.800759,4.377656,-8.813257,18,22.0,1.080171,1.319294,22.137494,22.5,30.136986
13,Amapá,13,6.0,3.256472,1.495308,-54.081952,4,2.0,1.001991,0.498436,-50.255449,30.769231,33.333333
14,Amazonas,103,77.0,4.883824,3.616373,-25.952019,23,29.0,1.090563,1.362011,24.890637,22.330097,37.662338

In [58]:
# Selecionando os dados de homicídios de mulheres e feminicídios
mulheres = df_t24.iloc[
    9:38,
    [0, 1, 2, 3, 4, 6, 7, 8, 9, 11, 12]
].copy()

# Exibindo os primeiros registros
mulheres.head()

,0,1,2,3,4,6,7,8,9,11,12
9,Brasil,3937,3700.0,3.630458,3.396943,1475,1492.0,1.360154,1.369794,37.465075,40.324324
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Acre,15,13.0,3.432942,2.962058,10,8.0,2.288628,1.822805,66.666667,61.538462
12,Alagoas,80,73.0,4.800759,4.377656,18,22.0,1.080171,1.319294,22.5,30.136986
13,Amapá,13,6.0,3.256472,1.495308,4,2.0,1.001991,0.498436,30.769231,33.333333

In [59]:
# Renomeando as colunas 
mulheres.columns = [
    'uf',
    'homicidios_mulheres_2023',
    'homicidios_mulheres_2024',
    'taxa_homicidios_2023',
    'taxa_homicidios_2024',
    'feminicidios_2023',
    'feminicidios_2024',
    'taxa_feminicidios_2023',
    'taxa_feminicidios_2024',
    'proporcao_feminicidios_2023',
    'proporcao_feminicidios_2024'
]

# Removendo linhas vazias
mulheres = mulheres.dropna(how='all')

# Exibindo os primeiros registros
mulheres.head()

,uf,homicidios_mulheres_2023,homicidios_mulheres_2024,taxa_homicidios_2023,taxa_homicidios_2024,feminicidios_2023,feminicidios_2024,taxa_feminicidios_2023,taxa_feminicidios_2024,proporcao_feminicidios_2023,proporcao_feminicidios_2024
9,Brasil,3937,3700.0,3.630458,3.396943,1475,1492.0,1.360154,1.369794,37.465075,40.324324
11,Acre,15,13.0,3.432942,2.962058,10,8.0,2.288628,1.822805,66.666667,61.538462
12,Alagoas,80,73.0,4.800759,4.377656,18,22.0,1.080171,1.319294,22.5,30.136986
13,Amapá,13,6.0,3.256472,1.495308,4,2.0,1.001991,0.498436,30.769231,33.333333
14,Amazonas,103,77.0,4.883824,3.616373,23,29.0,1.090563,1.362011,22.330097,37.662338

In [60]:
# Verificando a quantidade de linhas e colunas
mulheres.shape

(28, 11)

In [61]:
# Verificando se existem valores nulos
mulheres.isnull().sum()

uf                             0
homicidios_mulheres_2023       0
homicidios_mulheres_2024       0
taxa_homicidios_2023           0
taxa_homicidios_2024           0
feminicidios_2023              0
feminicidios_2024              0
taxa_feminicidios_2023         0
taxa_feminicidios_2024         0
proporcao_feminicidios_2023    0
proporcao_feminicidios_2024    0
dtype: int64

In [62]:
# Verificando os tipos das colunas
mulheres.dtypes

uf                                 str
homicidios_mulheres_2023        object
homicidios_mulheres_2024       float64
taxa_homicidios_2023            object
taxa_homicidios_2024           float64
feminicidios_2023               object
feminicidios_2024              float64
taxa_feminicidios_2023          object
taxa_feminicidios_2024         float64
proporcao_feminicidios_2023     object
proporcao_feminicidios_2024     object
dtype: object

In [63]:
# Definindo as colunas que precisam ser verificadas
colunas_verificar = [
    'homicidios_mulheres_2023',
    'taxa_homicidios_2023',
    'feminicidios_2023',
    'taxa_feminicidios_2023',
    'proporcao_feminicidios_2023'
]

# Verifica os tipos dos valores de cada coluna
for coluna in colunas_verificar:
    print(f"\n{coluna}")
    print(mulheres[coluna].apply(type).value_counts())

homicidios_mulheres_2023
homicidios_mulheres_2023
<class 'int'>    28
Name: count, dtype: int64

taxa_homicidios_2023
taxa_homicidios_2023
<class 'float'>    28
Name: count, dtype: int64

feminicidios_2023
feminicidios_2023
<class 'int'>    28
Name: count, dtype: int64

taxa_feminicidios_2023
taxa_feminicidios_2023
<class 'float'>    28
Name: count, dtype: int64

proporcao_feminicidios_2023
proporcao_feminicidios_2023
<class 'float'>    27
<class 'int'>       1
Name: count, dtype: int64

In [64]:
# Definindo as colunas de números absolutos
colunas_inteiras = [
    'homicidios_mulheres_2023',
    'homicidios_mulheres_2024',
    'feminicidios_2023',
    'feminicidios_2024'
]

# Converte os números absolutos para inteiro
for coluna in colunas_inteiras:
    mulheres[coluna] = pd.to_numeric(mulheres[coluna]).astype(int)


# Define as colunas de taxas e proporções
colunas_decimais = [
    'taxa_homicidios_2023',
    'taxa_homicidios_2024',
    'taxa_feminicidios_2023',
    'taxa_feminicidios_2024',
    'proporcao_feminicidios_2023',
    'proporcao_feminicidios_2024'
]

# Convertendo as taxas e proporções para valores numéricos
for coluna in colunas_decimais:
    mulheres[coluna] = pd.to_numeric(mulheres[coluna])

In [65]:
# Conferindo os tipos após a conversão
mulheres.dtypes

uf                                 str
homicidios_mulheres_2023         int64
homicidios_mulheres_2024         int64
taxa_homicidios_2023           float64
taxa_homicidios_2024           float64
feminicidios_2023                int64
feminicidios_2024                int64
taxa_feminicidios_2023         float64
taxa_feminicidios_2024         float64
proporcao_feminicidios_2023    float64
proporcao_feminicidios_2024    float64
dtype: object

In [66]:
# Criando a base de homicídios de mulheres para 2023
homicidios_mulheres_2023 = mulheres[
    ['uf', 'homicidios_mulheres_2023', 'taxa_homicidios_2023']
].copy()

homicidios_mulheres_2023.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

homicidios_mulheres_2023['ano'] = 2023
homicidios_mulheres_2023['indicador'] = 'Homicídios de mulheres'


# Criando a base de homicídios de mulheres para 2024
homicidios_mulheres_2024 = mulheres[
    ['uf', 'homicidios_mulheres_2024', 'taxa_homicidios_2024']
].copy()

homicidios_mulheres_2024.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

homicidios_mulheres_2024['ano'] = 2024
homicidios_mulheres_2024['indicador'] = 'Homicídios de mulheres'

In [67]:
# Unindo os dados de homicídios de mulheres de 2023 e 2024
homicidios_mulheres_long = pd.concat([
    homicidios_mulheres_2023,
    homicidios_mulheres_2024
], ignore_index=True)

# Padronizando a ordem das colunas
homicidios_mulheres_long = homicidios_mulheres_long[
    ['uf', 'ano', 'indicador', 'ocorrencias', 'taxa_100_mil']
]

# Exibindo os primeiros registros
homicidios_mulheres_long.head()

         uf   ano               indicador  ocorrencias  taxa_100_mil
0    Brasil  2023  Homicídios de mulheres         3937      3.630458
1      Acre  2023  Homicídios de mulheres           15      3.432942
2   Alagoas  2023  Homicídios de mulheres           80      4.800759
3     Amapá  2023  Homicídios de mulheres           13      3.256472
4  Amazonas  2023  Homicídios de mulheres          103      4.883824

In [68]:
# Criando a base de feminicídios para 2023
feminicidios_2023 = mulheres[
    ['uf', 'feminicidios_2023', 'taxa_feminicidios_2023']
].copy()

feminicidios_2023.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

feminicidios_2023['ano'] = 2023
feminicidios_2023['indicador'] = 'Feminicídios'


# Criando a base de feminicídios para 2024
feminicidios_2024 = mulheres[
    ['uf', 'feminicidios_2024', 'taxa_feminicidios_2024']
].copy()

feminicidios_2024.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

feminicidios_2024['ano'] = 2024
feminicidios_2024['indicador'] = 'Feminicídios'

In [69]:
# Unindo os dados de feminicídios de 2023 e 2024
feminicidios_long = pd.concat([
    feminicidios_2023,
    feminicidios_2024
], ignore_index=True)

# Padronizando a ordem das colunas
feminicidios_long = feminicidios_long[
    ['uf', 'ano', 'indicador', 'ocorrencias', 'taxa_100_mil']
]

# Exibindo os primeiros registros
feminicidios_long.head()

         uf   ano     indicador  ocorrencias  taxa_100_mil
0    Brasil  2023  Feminicídios         1475      1.360154
1      Acre  2023  Feminicídios           10      2.288628
2   Alagoas  2023  Feminicídios           18      1.080171
3     Amapá  2023  Feminicídios            4      1.001991
4  Amazonas  2023  Feminicídios           23      1.090563

In [70]:
# Criando a base de proporção de feminicídios para 2023
proporcao_2023 = mulheres[
    ['uf', 'proporcao_feminicidios_2023']
].copy()

proporcao_2023.columns = [
    'uf', 'proporcao_percentual'
]

proporcao_2023['ano'] = 2023
proporcao_2023['indicador'] = 'Proporção de feminicídios'


# Criando a base de proporção de feminicídios para 2024
proporcao_2024 = mulheres[
    ['uf', 'proporcao_feminicidios_2024']
].copy()

proporcao_2024.columns = [
    'uf', 'proporcao_percentual'
]

proporcao_2024['ano'] = 2024
proporcao_2024['indicador'] = 'Proporção de feminicídios'

In [71]:
# Unindo os dados de proporção de feminicídios de 2023 e 2024
proporcao_feminicidios_long = pd.concat([
    proporcao_2023,
    proporcao_2024
], ignore_index=True)

# Padronizando a ordem das colunas
proporcao_feminicidios_long = proporcao_feminicidios_long[
    ['uf', 'ano', 'indicador', 'proporcao_percentual']
]

# Exibindo os primeiros registros
proporcao_feminicidios_long.head()

         uf   ano                  indicador  proporcao_percentual
0    Brasil  2023  Proporção de feminicídios             37.465075
1      Acre  2023  Proporção de feminicídios             66.666667
2   Alagoas  2023  Proporção de feminicídios             22.500000
3     Amapá  2023  Proporção de feminicídios             30.769231
4  Amazonas  2023  Proporção de feminicídios             22.330097

In [72]:
# Unindo os indicadores de homicídios de mulheres e feminicídios
mulheres_long = pd.concat([
    homicidios_mulheres_long,
    feminicidios_long
], ignore_index=True)

# Exibindo os primeiros registros
mulheres_long.head()

         uf   ano               indicador  ocorrencias  taxa_100_mil
0    Brasil  2023  Homicídios de mulheres         3937      3.630458
1      Acre  2023  Homicídios de mulheres           15      3.432942
2   Alagoas  2023  Homicídios de mulheres           80      4.800759
3     Amapá  2023  Homicídios de mulheres           13      3.256472
4  Amazonas  2023  Homicídios de mulheres          103      4.883824

In [73]:
# Verificando a quantidade de linhas e colunas
mulheres_long.shape

(112, 5)

In [74]:
# Verifica a quantidade de registros por indicador
mulheres_long['indicador'].value_counts()

indicador
Homicídios de mulheres    56
Feminicídios              56
Name: count, dtype: int64

In [75]:
# Verificando se existem valores nulos
mulheres_long.isnull().sum()

uf              0
ano             0
indicador       0
ocorrencias     0
taxa_100_mil    0
dtype: int64

## Consolidação dos dados tratados

Nesta etapa, as bases tratadas são consolidadas em um único conjunto de dados, mantendo a padronização por Unidade da Federação, ano, indicador, número de ocorrências e taxa por 100 mil habitantes.

In [76]:
# Consolidando os principais indicadores em uma única base
dados_consolidados = pd.concat([
    mvi_long,
    latrocinio_long,
    celulares_long,
    mulheres_long
], ignore_index=True)

# Exibindo os primeiros registros
dados_consolidados.head()

         uf   ano indicador  ocorrencias  taxa_100_mil
0    Brasil  2023       MVI        46441     21.937677
1      Acre  2023       MVI          214     24.413004
2   Alagoas  2023       MVI         1210     37.593903
3     Amapá  2023       MVI          519     64.946116
4  Amazonas  2023       MVI         1406     33.155912

In [77]:
# Verificando a quantidade de linhas e colunas
dados_consolidados.shape

(448, 5)

In [78]:
# Verificando a quantidade de registros por indicador
dados_consolidados['indicador'].value_counts()

indicador
MVI                           56
Latrocínio - vítimas          56
Latrocínio - ocorrências      56
Roubo de celulares            56
Furto de celulares            56
Roubo e furto de celulares    56
Homicídios de mulheres        56
Feminicídios                  56
Name: count, dtype: int64

In [79]:
# Verificando se existem valores nulos
dados_consolidados.isnull().sum()

uf              0
ano             0
indicador       0
ocorrencias     0
taxa_100_mil    0
dtype: int64

In [80]:
# Verificando se existem registros duplicados
dados_consolidados.duplicated().sum()

np.int64(0)

In [81]:
# Removendo referências de notas dos nomes das UFs
dados_consolidados['uf'] = dados_consolidados['uf'].str.replace(
    r'\s*\(\d+\)$',
    '',
    regex=True
)

# Removendo referências de notas dos nomes das UFs
proporcao_feminicidios_long['uf'] = proporcao_feminicidios_long['uf'].str.replace(
    r'\s*\(\d+\)$',
    '',
    regex=True
)

In [82]:
# Salvando a base consolidada em CSV
dados_consolidados.to_csv(
    '../data/processed/dados_consolidados.csv',
    index=False,
    encoding='utf-8-sig'
)

# Salvando a base de proporção de feminicídios em CSV
proporcao_feminicidios_long.to_csv(
    '../data/processed/proporcao_feminicidios.csv',
    index=False,
    encoding='utf-8-sig'
)

In [83]:
# Verificanco se os arquivos foram salvos na pasta processed
import os

os.listdir('../data/processed')

['dados_consolidados.csv', 'proporcao_feminicidios.csv']