In [20]:
import pandas as pd

## Inspeção e tratamento da Tabela 01 — Mortes Violentas Intencionais (MVI)

Nesta etapa, serão selecionados e tratados os dados de Mortes Violentas Intencionais (MVI) por Unidade da Federação, referentes aos anos de 2023 e 2024.

In [21]:
arquivo = "../data/raw/anuario_seguranca_publica_2025.xlsx"

In [22]:
excel = pd.ExcelFile(arquivo)

excel.sheet_names

['Índice',
 'T01',
 'T02',
 'P01',
 'Q01',
 'T03',
 'T04',
 'T05',
 'T06',
 'T07',
 'T08',
 'P02',
 'T09',
 'T10',
 'P03',
 'Q02',
 'Q03',
 'T11',
 'G26',
 'T12',
 'T13',
 'T14',
 'T15',
 'T16',
 'T17',
 'T18',
 'P04',
 'Q04',
 'Q05',
 'Q06',
 'T19',
 'P05',
 'T20',
 'T21',
 'P06',
 'T22',
 'T23',
 'T24',
 'T25',
 'T26',
 'T27',
 'T28',
 'T29',
 'T30',
 'T31',
 'T32',
 'T33',
 'Q07',
 'P07',
 'T34',
 'T35',
 'T36',
 'T37',
 'T38',
 'T39',
 'P08',
 'Q08',
 'T40',
 'T41',
 'T42',
 'T43',
 'T44',
 'T45',
 'T46',
 'T47',
 'T48',
 'T49',
 'T50',
 'T51',
 'T52',
 'T53',
 'P09',
 'P10',
 'G66',
 'P11',
 'P12',
 'T54',
 'T55',
 'T56',
 'T57',
 'T58',
 'T59',
 'T60',
 'T61',
 'T62',
 'T63',
 'T64',
 'T65',
 'T66',
 'T67',
 'T68',
 'T69',
 'T70',
 'P13',
 'T71',
 'G79',
 'T72',
 'T73',
 'T74',
 'T75',
 'T76',
 'T77',
 'T78',
 'T79',
 'T80',
 'T81',
 'T82',
 'T83',
 'T84',
 'T85',
 'G80',
 'T86',
 'T87',
 'T88',
 'T89',
 'T90',
 'T91',
 'T92',
 'T93',
 'T94',
 'T95',
 'T96',
 'T97',
 'G81',
 'T98',
 'T99',
 'T100',
 'T101',
 'T102',
 'G82',
 'P14',
 'T103',
 'T104',
 'T105',
 'T106',
 'T107',
 'T108',
 'T109',
 'T110',
 'T111',
 'T112',
 'T113',
 'T114',
 'T115',
 'T116',
 'G86',
 'T117',
 'T118',
 'T119',
 'T120',
 'T121',
 'T122',
 'T123',
 'T124',
 'T125',
 'T126',
 'T127',
 'T128',
 'T129',
 'T130',
 'T131',
 'T132',
 'T133',
 'T134',
 'T135',
 'T136',
 'T137',
 'T138',
 'T139',
 'P15',
 'T140',
 'T141',
 'T142',
 'T143',
 'T144',
 'T145',
 'G90',
 'G91',
 'P16']

In [23]:
tabelas_projeto = ['T01', 'T04', 'T13', 'T24']

for tabela in tabelas_projeto:
    print(tabela, "->", tabela in excel.sheet_names)

T01 -> True
T04 -> True
T13 -> True
T24 -> True

In [24]:
df_t01 = pd.read_excel(arquivo, sheet_name='T01', header=None)

df_t01.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,TABELA 01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(Voltar ao índice)
1,Mortes violentas intencionais (1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Brasil e Unidades da Federação – 2023-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Brasil e Unidades da Federação,Crimes Violentos Letais Intencionais - CVLI,NaN,NaN,NaN,NaN,NaN,Policiais Civis e Militares Vítimas de CVLI,NaN,Morte Decorrente de Intervenção Policial (em s...,NaN,Mortes Violentas Intencionais - MVI,NaN,NaN,NaN,NaN
5,NaN,Homicídio Doloso,NaN,Latrocínio,NaN,Lesão Corporal Seguida de Morte,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Ns. Absolutos,NaN,Ns. Absolutos,NaN,Ns. Absolutos,NaN,Ns. Absolutos,NaN,Ns. Absolutos,NaN,Ns. Absolutos,NaN,Taxa (2),NaN,Variação (%)
8,NaN,2023 (3),2024.0,2023 (3),2024.0,2023 (3),2024.0,2023 (3),2024,2023 (3),2024.0,2023 (3),2024.0,2023,2024.000000,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Brasil,38653,36427.0,1002,965.0,628,760.0,178,170,6413,6243.0,46441,44127.0,21.937677,20.757466,-5.379835
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Acre,190,164.0,5,1.0,4,4.0,-,-,15,10.0,214,179.0,24.413004,20.326334,-16.739726
13,Alagoas,1122,1054.0,18,6.0,4,6.0,2,4,66,75.0,1210,1141.0,37.593903,35.433638,-5.746317
14,Amapá,307,218.0,13,4.0,16,3.0,-,-,183,137.0,519,362.0,64.946116,45.090099,-30.573063

In [25]:
mvi = df_t01.iloc[10:39, [0, 11, 12, 13, 14]].copy()

mvi.head()

         0      11       12         13         14
10   Brasil  46441  44127.0  21.937677  20.757466
11      NaN    NaN      NaN        NaN        NaN
12     Acre    214    179.0  24.413004  20.326334
13  Alagoas   1210   1141.0  37.593903  35.433638
14    Amapá    519    362.0  64.946116  45.090099

In [26]:
mvi.columns = [
    'uf',
    'mvi_2023',
    'mvi_2024',
    'taxa_2023',
    'taxa_2024'
]

mvi.head()

         uf mvi_2023  mvi_2024  taxa_2023  taxa_2024
10   Brasil    46441   44127.0  21.937677  20.757466
11      NaN      NaN       NaN        NaN        NaN
12     Acre      214     179.0  24.413004  20.326334
13  Alagoas     1210    1141.0  37.593903  35.433638
14    Amapá      519     362.0  64.946116  45.090099

In [27]:
mvi = mvi.dropna(how='all')

mvi.head()

          uf mvi_2023  mvi_2024  taxa_2023  taxa_2024
10    Brasil    46441   44127.0  21.937677  20.757466
12      Acre      214     179.0  24.413004  20.326334
13   Alagoas     1210    1141.0  37.593903  35.433638
14     Amapá      519     362.0  64.946116  45.090099
15  Amazonas     1406    1173.0  33.155912  27.398803

In [28]:
mvi.tail()

                uf mvi_2023  mvi_2024  taxa_2023  taxa_2024
34         Roraima      177     133.0  25.457736  18.554869
35  Santa Catarina      674     685.0   8.502359   8.500403
36   São Paulo (5)     3480    3751.0   7.589873   8.159102
37         Sergipe      689     522.0  30.192893  22.784044
38       Tocantins      430     312.0  27.437626  19.780111

In [29]:
mvi.shape

(28, 5)

In [30]:
mvi.dtypes

uf               str
mvi_2023      object
mvi_2024     float64
taxa_2023     object
taxa_2024    float64
dtype: object

In [31]:
mvi['mvi_2023'].apply(type).value_counts()

mvi_2023
<class 'int'>    28
Name: count, dtype: int64

In [32]:
mvi['taxa_2023'].apply(type).value_counts()

taxa_2023
<class 'float'>    28
Name: count, dtype: int64

In [33]:
mvi['mvi_2023'] = pd.to_numeric(mvi['mvi_2023'])
mvi['mvi_2024'] = pd.to_numeric(mvi['mvi_2024']).astype(int)

mvi['taxa_2023'] = pd.to_numeric(mvi['taxa_2023'])
mvi['taxa_2024'] = pd.to_numeric(mvi['taxa_2024'])

In [34]:
mvi.dtypes

uf               str
mvi_2023       int64
mvi_2024       int64
taxa_2023    float64
taxa_2024    float64
dtype: object

In [35]:
mvi.isnull().sum()

uf           0
mvi_2023     0
mvi_2024     0
taxa_2023    0
taxa_2024    0
dtype: int64

In [36]:
# Transformação para o formato: uf | ano | indicador | ocorrencias | taxa_100_mil.

mvi_2023 = mvi[['uf', 'mvi_2023', 'taxa_2023']].copy()
mvi_2023.columns = ['uf', 'ocorrencias', 'taxa_100_mil']
mvi_2023['ano'] = 2023
mvi_2023['indicador'] = 'MVI'

mvi_2024 = mvi[['uf', 'mvi_2024', 'taxa_2024']].copy()
mvi_2024.columns = ['uf', 'ocorrencias', 'taxa_100_mil']
mvi_2024['ano'] = 2024
mvi_2024['indicador'] = 'MVI'

In [37]:
mvi_long = pd.concat([mvi_2023, mvi_2024], ignore_index=True)

mvi_long = mvi_long[
    ['uf', 'ano', 'indicador', 'ocorrencias', 'taxa_100_mil']
]

mvi_long.head()

         uf   ano indicador  ocorrencias  taxa_100_mil
0    Brasil  2023       MVI        46441     21.937677
1      Acre  2023       MVI          214     24.413004
2   Alagoas  2023       MVI         1210     37.593903
3     Amapá  2023       MVI          519     64.946116
4  Amazonas  2023       MVI         1406     33.155912

In [38]:
mvi_long.shape

(56, 5)

In [39]:
mvi_long.tail()

                uf   ano indicador  ocorrencias  taxa_100_mil
51         Roraima  2024       MVI          133     18.554869
52  Santa Catarina  2024       MVI          685      8.500403
53   São Paulo (5)  2024       MVI         3751      8.159102
54         Sergipe  2024       MVI          522     22.784044
55       Tocantins  2024       MVI          312     19.780111

## Inspeção e tratamento da Tabela 04 — Latrocínio

Nesta etapa, serão analisados os dados de latrocínio por Unidade da Federação, considerando o número de vítimas e o número de ocorrências nos anos de 2023 e 2024.

In [40]:
df_t04 = pd.read_excel(
    arquivo,
    sheet_name='T04',
    header=None
)

df_t04.head(15)

,0,1,2,3,4,5,6,7,8,9,10
0,TABELA 04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(Voltar ao índice)
1,"Latrocínio, por número de vítimas e número de ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Brasil e Unidades da Federação – 2023-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Brasil e Unidades da Federação,Latrocínio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Nº de Vítimas,NaN,NaN,NaN,NaN,Nº de Ocorrências,NaN,NaN,NaN,NaN
6,NaN,Ns. Absolutos,NaN,Taxas (1),NaN,Variação (%),Ns. Absolutos,NaN,Taxas (1),NaN,Variação (%)
7,NaN,2023 (2),2024.0,2023,2024.000000,NaN,2023 (2),2024.0,2023,2024.000000,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Brasil,1002,965.0,0.473322,0.453939,-4.095176,979,944.0,0.462457,0.444060,-3.978129
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Acre,5,1.0,0.570397,0.113555,-80.091957,4,1.0,0.456318,0.113555,-75.114946
12,Alagoas,18,6.0,0.559248,0.186329,-66.682163,18,5.0,0.559248,0.155274,-72.235136
13,Amapá,13,4.0,1.626781,0.498233,-69.373072,13,4.0,1.626781,0.498233,-69.373072
14,Amazonas,36,22.0,0.848942,0.513874,-39.468966,35,22.0,0.825361,0.513874,-37.739508

In [41]:
latrocinio = df_t04.iloc[9:38, [0, 1, 2, 3, 4, 6, 7, 8, 9]].copy()

latrocinio.head()

          0     1      2         3         4    6      7         8         9
9    Brasil  1002  965.0  0.473322  0.453939  979  944.0  0.462457  0.444060
10      NaN   NaN    NaN       NaN       NaN  NaN    NaN       NaN       NaN
11     Acre     5    1.0  0.570397  0.113555    4    1.0  0.456318  0.113555
12  Alagoas    18    6.0  0.559248  0.186329   18    5.0  0.559248  0.155274
13    Amapá    13    4.0  1.626781  0.498233   13    4.0  1.626781  0.498233

In [43]:
# Renomeando as colunas
latrocinio.columns = [
    'uf',
    'vitimas_2023',
    'vitimas_2024',
    'taxa_vitimas_2023',
    'taxa_vitimas_2024',
    'ocorrencias_2023',
    'ocorrencias_2024',
    'taxa_ocorrencias_2023',
    'taxa_ocorrencias_2024'
]

# Removendo linhas vazias
latrocinio = latrocinio.dropna(how='all')

latrocinio.head()

,uf,vitimas_2023,vitimas_2024,taxa_vitimas_2023,taxa_vitimas_2024,ocorrencias_2023,ocorrencias_2024,taxa_ocorrencias_2023,taxa_ocorrencias_2024
9,Brasil,1002,965.0,0.473322,0.453939,979,944.0,0.462457,0.444060
11,Acre,5,1.0,0.570397,0.113555,4,1.0,0.456318,0.113555
12,Alagoas,18,6.0,0.559248,0.186329,18,5.0,0.559248,0.155274
13,Amapá,13,4.0,1.626781,0.498233,13,4.0,1.626781,0.498233
14,Amazonas,36,22.0,0.848942,0.513874,35,22.0,0.825361,0.513874

In [44]:
latrocinio.shape

(28, 9)

In [45]:
latrocinio.tail()

,uf,vitimas_2023,vitimas_2024,taxa_vitimas_2023,taxa_vitimas_2024,ocorrencias_2023,ocorrencias_2024,taxa_ocorrencias_2023,taxa_ocorrencias_2024
33,Roraima,9,6.0,1.294461,0.837062,9,6.0,1.294461,0.837062
34,Santa Catarina,11,16.0,0.138763,0.198550,11,16.0,0.138763,0.198550
35,São Paulo,166,170.0,0.362046,0.369781,163,166.0,0.355503,0.361080
36,Sergipe,6,7.0,0.262928,0.305533,6,7.0,0.262928,0.305533
37,Tocantins,19,6.0,1.21236,0.380387,17,6.0,1.084743,0.380387

In [46]:
latrocinio.isnull().sum()

uf                       0
vitimas_2023             0
vitimas_2024             0
taxa_vitimas_2023        0
taxa_vitimas_2024        0
ocorrencias_2023         0
ocorrencias_2024         0
taxa_ocorrencias_2023    0
taxa_ocorrencias_2024    0
dtype: int64

In [47]:
latrocinio.dtypes

uf                           str
vitimas_2023              object
vitimas_2024             float64
taxa_vitimas_2023         object
taxa_vitimas_2024        float64
ocorrencias_2023          object
ocorrencias_2024         float64
taxa_ocorrencias_2023     object
taxa_ocorrencias_2024    float64
dtype: object

In [48]:
colunas_verificar = [
    'vitimas_2023',
    'taxa_vitimas_2023',
    'ocorrencias_2023',
    'taxa_ocorrencias_2023'
]

for coluna in colunas_verificar:
    print(f"\n{coluna}")
    print(latrocinio[coluna].apply(type).value_counts())

vitimas_2023
vitimas_2023
<class 'int'>    28
Name: count, dtype: int64

taxa_vitimas_2023
taxa_vitimas_2023
<class 'float'>    28
Name: count, dtype: int64

ocorrencias_2023
ocorrencias_2023
<class 'int'>    28
Name: count, dtype: int64

taxa_ocorrencias_2023
taxa_ocorrencias_2023
<class 'float'>    28
Name: count, dtype: int64

In [49]:
# Convertendo contagens para inteiro
latrocinio['vitimas_2023'] = pd.to_numeric(
    latrocinio['vitimas_2023']
).astype(int)

latrocinio['vitimas_2024'] = pd.to_numeric(
    latrocinio['vitimas_2024']
).astype(int)

latrocinio['ocorrencias_2023'] = pd.to_numeric(
    latrocinio['ocorrencias_2023']
).astype(int)

latrocinio['ocorrencias_2024'] = pd.to_numeric(
    latrocinio['ocorrencias_2024']
).astype(int)

# Convertendo taxas para valores numéricos
latrocinio['taxa_vitimas_2023'] = pd.to_numeric(
    latrocinio['taxa_vitimas_2023']
)

latrocinio['taxa_vitimas_2024'] = pd.to_numeric(
    latrocinio['taxa_vitimas_2024']
)

latrocinio['taxa_ocorrencias_2023'] = pd.to_numeric(
    latrocinio['taxa_ocorrencias_2023']
)

latrocinio['taxa_ocorrencias_2024'] = pd.to_numeric(
    latrocinio['taxa_ocorrencias_2024']
)

In [50]:
latrocinio.dtypes

uf                           str
vitimas_2023               int64
vitimas_2024               int64
taxa_vitimas_2023        float64
taxa_vitimas_2024        float64
ocorrencias_2023           int64
ocorrencias_2024           int64
taxa_ocorrencias_2023    float64
taxa_ocorrencias_2024    float64
dtype: object

In [52]:
# Transformando a tabela para o formato longo, preservando a diferença entre vítimas e ocorrências
# Dados de vítimas - 2023
latrocinio_vitimas_2023 = latrocinio[
    ['uf', 'vitimas_2023', 'taxa_vitimas_2023']
].copy()

latrocinio_vitimas_2023.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

latrocinio_vitimas_2023['ano'] = 2023
latrocinio_vitimas_2023['indicador'] = 'Latrocínio - vítimas'


# Dados de vítimas - 2024
latrocinio_vitimas_2024 = latrocinio[
    ['uf', 'vitimas_2024', 'taxa_vitimas_2024']
].copy()

latrocinio_vitimas_2024.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

latrocinio_vitimas_2024['ano'] = 2024
latrocinio_vitimas_2024['indicador'] = 'Latrocínio - vítimas'

In [53]:
# Dados de ocorrências - 2023
latrocinio_ocorrencias_2023 = latrocinio[
    ['uf', 'ocorrencias_2023', 'taxa_ocorrencias_2023']
].copy()

latrocinio_ocorrencias_2023.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

latrocinio_ocorrencias_2023['ano'] = 2023
latrocinio_ocorrencias_2023['indicador'] = 'Latrocínio - ocorrências'


# Dados de ocorrências - 2024
latrocinio_ocorrencias_2024 = latrocinio[
    ['uf', 'ocorrencias_2024', 'taxa_ocorrencias_2024']
].copy()

latrocinio_ocorrencias_2024.columns = [
    'uf', 'ocorrencias', 'taxa_100_mil'
]

latrocinio_ocorrencias_2024['ano'] = 2024
latrocinio_ocorrencias_2024['indicador'] = 'Latrocínio - ocorrências'

In [54]:
# Juntando os dados de vítimas e ocorrências
latrocinio_long = pd.concat([
    latrocinio_vitimas_2023,
    latrocinio_vitimas_2024,
    latrocinio_ocorrencias_2023,
    latrocinio_ocorrencias_2024
], ignore_index=True)

latrocinio_long = latrocinio_long[
    ['uf', 'ano', 'indicador', 'ocorrencias', 'taxa_100_mil']
]

latrocinio_long.head()

         uf   ano             indicador  ocorrencias  taxa_100_mil
0    Brasil  2023  Latrocínio - vítimas         1002      0.473322
1      Acre  2023  Latrocínio - vítimas            5      0.570397
2   Alagoas  2023  Latrocínio - vítimas           18      0.559248
3     Amapá  2023  Latrocínio - vítimas           13      1.626781
4  Amazonas  2023  Latrocínio - vítimas           36      0.848942

In [55]:
latrocinio_long.shape

(112, 5)

In [57]:
latrocinio_long['indicador'].value_counts()

indicador
Latrocínio - vítimas        56
Latrocínio - ocorrências    56
Name: count, dtype: int64

In [58]:
latrocinio_long.isnull().sum()

uf              0
ano             0
indicador       0
ocorrencias     0
taxa_100_mil    0
dtype: int64